name: Backend CI Maven

on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Atualizar código
      uses: actions/checkout@v4

    - name: Travar versão do Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto' 
        java-version: '17'


    - name : Baixar dependências
      run: |
        cd projeto-volt
        mvn clean install --batch-mode --quiet -DargLine="--add-opens jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED"

    
    - name: Gerar artefato Github com os arquivos de build
      uses: actions/upload-artifact@v4
      with:
         name: projeto-volt
         path: projeto-volt/target/*jar

  deploy:
      needs: build
      runs-on: ubuntu-latest

      steps:
          - name: Recuperar artefato do build
            uses: actions/download-artifact@v4
            with:
               name: projeto-volt
               path: projeto-volt/target/*jar
            
         
