name: Backend CI Maven

on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Atualizar código
      uses: actions/checkout@v2
    
    - name: Travar versão do Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto' 
        java-version: '17'

    - name : Baixar dependências
      run: | 
        ENV_VARS="DB_DRIVER=com.mysql.cj.jdbc.Driver;DB_PASSWORD=sptech;DB_URL=jdbc:mysql://localhost:3306/bd_volt;DB_USERNAME=sptech;JWT_SECRET=1D08EWyxTWMzgPWZL2FNcQjOSfLLyrDISspdBkWFxJUOadpcNNblmbNT1kF2zR22AWcMUF1HPMkCSApDGyiO6eFqfwCFPxd6"
        export $ENV_VARS
        mvn clean package --file ./projeto-volt/pom.xml -Dmaven.test.skip=true
        
    - name : Gerar arquivo jar
      run: mvn clean package -Dmaven.test.skip=true

    - name: Gerar artefato Github com os arquivos de build
      uses: actions/upload-artifact@v4
      with:
        name: projeto-volt
        path: projeto-volt/target/*jar

  deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
        - name: Recuperar artefato do build
          uses: actions/download-artifact@v4
          with:
            name: projeto-volt
            path: projeto-volt/target/*jar
            
         
