name: Backend CI Maven

on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Travar versão do Java
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'corretto' 
        java-version: '17'
        cache : maven

    - name : Baixar dependências
      run: mvn -B package --file pom.xml
